import {
  BeachAccessRounded,
  BrushRounded,
  BugReportRounded,
  BuildRounded,
  CelebrationRounded,
  DirectionsRunRounded,
  EmojiEmotionsRounded,
  EmojiFlagsRounded,
  ExploreRounded,
  ExtensionRounded,
  FamilyRestroomRounded,
  FlashOnRounded,
  GavelRounded,
  HourglassEmptyRounded,
  MenuBookRounded,
  MilitaryTechRounded,
  MusicNoteRounded,
  PublicRounded,
  ScheduleRounded,
  SecurityRounded,
  SportsEsportsRounded,
  SportsMmaRounded,
  SportsSoccerRounded,
  StyleRounded,
  ThreeSixtyRounded,
  TrackChangesRounded,
} from "@mui/icons-material";

export const categoryIcons = {
  action: <FlashOnRounded />,
  adventure: <ExploreRounded />,
  arcade: <SportsEsportsRounded />,
  battle_royale: <TrackChangesRounded />,
  card_game: <StyleRounded />,
  casual: <EmojiEmotionsRounded />,
  educational: <MenuBookRounded />,
  family: <FamilyRestroomRounded />,
  fighting: <SportsMmaRounded />,
  hack_and_slash: <GavelRounded />,
  idle_game: <HourglassEmptyRounded />,
  indie: <BrushRounded />,
  mmo: <PublicRounded />,
  moba: <SecurityRounded />,
  music: <MusicNoteRounded />,
  party_game: <CelebrationRounded />,
  platformer: <DirectionsRunRounded />,
  puzzle: <ExtensionRounded />,
  racing: <EmojiFlagsRounded />,
  rpg: <SecurityRounded />,
  rts: <ScheduleRounded />,
  sandbox: <BeachAccessRounded />,
  shooter: <SportsEsportsRounded />,
  simulation: <BuildRounded />,
  sports: <SportsSoccerRounded />,
  strategy: <ExtensionRounded />,
  survival: <BuildRounded />,
  tactical: <TrackChangesRounded />,
  tower_defense: <SecurityRounded />,
  trading_card_game: <StyleRounded />,
  visual_novel: <MenuBookRounded />,
  vr: <ThreeSixtyRounded />,
  wargame: <MilitaryTechRounded />,
  world_builder: <PublicRounded />,
  zombie: <BugReportRounded />,
} as const;

export type TranslationCategoryLabelType = keyof typeof categoryIcons;

export const translationCategoryDictionnaries: Record<
  string,
  Record<TranslationCategoryLabelType, string>
> = {
  en: {
    action: "Action",
    adventure: "Adventure",
    arcade: "Arcade",
    battle_royale: "Battle Royale",
    card_game: "Card Game",
    casual: "Casual",
    educational: "Educational",
    family: "Family",
    fighting: "Fighting",
    hack_and_slash: "Hack and Slash",
    idle_game: "Idle Game",
    indie: "Indie",
    mmo: "MMO",
    moba: "MOBA",
    music: "Music",
    party_game: "Party Game",
    platformer: "Platformer",
    puzzle: "Puzzle",
    racing: "Racing",
    rpg: "RPG",
    rts: "RTS",
    sandbox: "Sandbox",
    shooter: "Shooter",
    simulation: "Simulation",
    sports: "Sports",
    strategy: "Strategy",
    survival: "Survival",
    tactical: "Tactical",
    tower_defense: "Tower Defense",
    trading_card_game: "Trading Card Game",
    visual_novel: "Visual Novel",
    vr: "VR",
    wargame: "Wargame",
    world_builder: "World Builder",
    zombie: "Zombie",
  },
  fr: {
    action: "Action",
    adventure: "Aventure",
    arcade: "Arcade",
    battle_royale: "Battle Royale",
    card_game: "Jeu de cartes",
    casual: "Décontracté",
    educational: "Éducatif",
    family: "Famille",
    fighting: "Combat",
    hack_and_slash: "Hack and Slash",
    idle_game: "Jeu passif",
    indie: "Indépendant",
    mmo: "MMO",
    moba: "MOBA",
    music: "Musique",
    party_game: "Jeu de soirée",
    platformer: "Plateforme",
    puzzle: "Puzzle",
    racing: "Course",
    rpg: "RPG",
    rts: "RTS",
    sandbox: "Sandbox",
    shooter: "Tir",
    simulation: "Simulation",
    sports: "Sport",
    strategy: "Stratégie",
    survival: "Survie",
    tactical: "Tactique",
    tower_defense: "Tower Defense",
    trading_card_game: "Jeu de cartes à collectionner",
    visual_novel: "Roman visuel",
    vr: "VR",
    wargame: "Jeu de guerre",
    world_builder: "Constructeur de monde",
    zombie: "Zombie",
  },
} as const;
