export const currentLanguage: 'fr' | 'en' = 'fr';
import {
    AccountCircleRounded,
    PeopleRounded,
    GamepadRounded,
    CloudRounded,
    EmojiEventsRounded,
    SportsEsportsRounded,
    BuildRounded,
    SettingsApplicationsRounded,
    PhotoCameraRounded,
    VibrationRounded,
    LocalFireDepartmentRounded,
    LoopRounded,
    FlashOnRounded,
    StoreRounded,
    ReplayRounded,
    FaceRounded,
    ExtensionRounded,
    LocalMallRounded,
    ViewInArRounded,
    CloudDoneRounded,
} from '@mui/icons-material';

export const featureIcons: { [key in Label]: JSX.Element } = {
    singleplayer: <AccountCircleRounded />,
    multiplayer: <PeopleRounded />,
    co_op: <PeopleRounded />,
    cross_platform: <GamepadRounded />,
    online_multiplayer: <PeopleRounded />,
    cloud_saves: <CloudRounded />,
    achievements: <EmojiEventsRounded />,
    controller_support: <SportsEsportsRounded />,
    mod_support: <BuildRounded />,
    early_access: <SettingsApplicationsRounded />,
    free_to_play: <LocalMallRounded />,
    in_app_purchases: <StoreRounded />,
    vr_support: <ViewInArRounded />,
    ray_tracing: <FlashOnRounded />,
    photo_mode: <PhotoCameraRounded />,
    haptic_feedback: <VibrationRounded />,
    season_pass: <ReplayRounded />,
    esports: <SportsEsportsRounded />,
    procedural_generation: <LoopRounded />,
    character_customization: <FaceRounded />,
    sandbox_mode: <ExtensionRounded />,
    steam_workshop_support: <CloudDoneRounded />,
    roguelike_elements: <LocalFireDepartmentRounded />,
    permadeath: <SportsEsportsRounded />,
};
const labelList = [
    'singleplayer',
    'multiplayer',
    'co_op',
    'cross_platform',
    'online_multiplayer',
    'cloud_saves',
    'achievements',
    'controller_support',
    'mod_support',
    'early_access',
    'free_to_play',
    'in_app_purchases',
    'vr_support',
    'ray_tracing',
    'photo_mode',
    'haptic_feedback',
    'season_pass',
    'esports',
    'procedural_generation',
    'character_customization',
    'sandbox_mode',
    'steam_workshop_support',
    'roguelike_elements',
    'permadeath',
] as const;

type Label = typeof labelList[number];

export const translateFeature = (label: Label): string => translationDictionnaries[currentLanguage][label];

export const translationDictionnaries: { [language: string]: { [label in Label]: string } } = {
    // -------------------- English --------------------
    en: {
        singleplayer: "Singleplayer",
        multiplayer: "Multiplayer",
        co_op: "Co-op",
        cross_platform: "Cross-platform",
        online_multiplayer: "Online multiplayer",
        cloud_saves: "Cloud saves",
        achievements: "Achievements",
        controller_support: "Controller support",
        mod_support: "Mod support",
        early_access: "Early access",
        free_to_play: "Free-to-play",
        in_app_purchases: "In-app purchases",
        vr_support: "VR support",
        ray_tracing: "Ray tracing",
        photo_mode: "Photo mode",
        haptic_feedback: "Haptic feedback",
        season_pass: "Season pass",
        esports: "Esports",
        procedural_generation: "Procedural generation",
        character_customization: "Character customization",
        sandbox_mode: "Sandbox mode",
        steam_workshop_support: "Steam Workshop support",
        roguelike_elements: "Roguelike elements",
        permadeath: "Permadeath",
    },

    // -------------------- French --------------------
    fr: {
        singleplayer: "Solo",
        multiplayer: "Multijoueur",
        co_op: "Coop",
        cross_platform: "Multiplateforme",
        online_multiplayer: "Multijoueur en ligne",
        cloud_saves: "Sauvegardes cloud",
        achievements: "Succès",
        controller_support: "Support de manette",
        mod_support: "Support des mods",
        early_access: "Accès anticipé",
        free_to_play: "Gratuit avec achats",
        in_app_purchases: "Achats intégrés",
        vr_support: "Support VR",
        ray_tracing: "Ray tracing",
        photo_mode: "Mode photo",
        haptic_feedback: "Retour haptique",
        season_pass: "Pass saisonnier",
        esports: "Esports",
        procedural_generation: "Génération procédurale",
        character_customization: "Personnalisation de personnage",
        sandbox_mode: "Mode sandbox",
        steam_workshop_support: "Support Steam Workshop",
        roguelike_elements: "Éléments roguelike",
        permadeath: "Permamort",
    },
};