export const currentLanguage: "fr" | "en" = "fr";

const labelList = [
  "french",
  "french_belgium",
  "french_canada",
  "english_us",
  "english_uk",
  "english_canada",
  "english_australia",
  "spanish",
  "spanish_mexico",
  "portuguese",
  "portuguese_brazil",
  "german",
  "italian",
  "dutch",
  "dutch_belgium",
  "russian",
  "chinese_simplified",
  "chinese_traditional",
  "japanese",
  "korean",
  "arabic",
  "turkish",
  "polish",
  "swedish",
  "norwegian",
  "danish",
  "finnish",
  "czech",
  "hungarian",
  "greek",
] as const;

type Label = (typeof labelList)[number];

export const translateLanguage = (label: Label): string =>
  translationLanguageDictionnaries[currentLanguage][label];

export type TranslationLanguageLabelType = (typeof labelList)[number];

export const translationLanguageDictionnaries: {
  [language: string]: { [label in TranslationLanguageLabelType]: string };
} = {
  // -------------------- English --------------------
  en: {
    french: "French",
    french_belgium: "French (Belgium)",
    french_canada: "French (Canada)",
    english_us: "English (US)",
    english_uk: "English (UK)",
    english_canada: "English (Canada)",
    english_australia: "English (Australia)",
    spanish: "Spanish",
    spanish_mexico: "Spanish (Mexico)",
    portuguese: "Portuguese",
    portuguese_brazil: "Portuguese (Brazil)",
    german: "German",
    italian: "Italian",
    dutch: "Dutch",
    dutch_belgium: "Dutch (Belgium)",
    russian: "Russian",
    chinese_simplified: "Chinese (Simplified)",
    chinese_traditional: "Chinese (Traditional)",
    japanese: "Japanese",
    korean: "Korean",
    arabic: "Arabic",
    turkish: "Turkish",
    polish: "Polish",
    swedish: "Swedish",
    norwegian: "Norwegian",
    danish: "Danish",
    finnish: "Finnish",
    czech: "Czech",
    hungarian: "Hungarian",
    greek: "Greek",
  },
  // -------------------- French --------------------
  fr: {
    french: "Français",
    french_belgium: "Français (Belgique)",
    french_canada: "Français (Canada)",
    english_us: "Anglais (États-Unis)",
    english_uk: "Anglais (Royaume-Uni)",
    english_canada: "Anglais (Canada)",
    english_australia: "Anglais (Australie)",
    spanish: "Espagnol",
    spanish_mexico: "Espagnol (Mexique)",
    portuguese: "Portugais",
    portuguese_brazil: "Portugais (Brésil)",
    german: "Allemand",
    italian: "Italien",
    dutch: "Néerlandais",
    dutch_belgium: "Néerlandais (Belgique)",
    russian: "Russe",
    chinese_simplified: "Chinois (Simplifié)",
    chinese_traditional: "Chinois (Traditionnel)",
    japanese: "Japonais",
    korean: "Coréen",
    arabic: "Arabe",
    turkish: "Turc",
    polish: "Polonais",
    swedish: "Suédois",
    norwegian: "Norvégien",
    danish: "Danois",
    finnish: "Finnois",
    czech: "Tchèque",
    hungarian: "Hongrois",
    greek: "Grec",
  },
};
