export const currentLanguage: 'fr' | 'en' = 'fr';

const labelList = [
    'english',
    'french',
    'french_belgium',
    'spanish',
    'german',
    'italian',
    'japanese',
    'chinese',
    'korean',
    'russian',
    'portuguese',
    'dutch',
    'swedish',
    'norwegian',
    'danish',
    'finnish',
    'polish',
    'czech',
    'hungarian',
    'greek',
    'turkish',
    'arabic',
    'hebrew',
    'hindi',
    'thai',
    'vietnamese',
    'indonesian',
] as const;

type Label = typeof labelList[number];

export const translateLanguage = (label: Label): string => translationDictionnaries[currentLanguage][label];

export const translationDictionnaries: { [language: string]: { [label in Label]: string } } = {
    // -------------------- English --------------------
    en: {
        english: "English",
        french: "French",
        french_belgium: "French (Belgium)",
        spanish: "Spanish",
        german: "German",
        italian: "Italian",
        japanese: "Japanese",
        chinese: "Chinese",
        korean: "Korean",
        russian: "Russian",
        portuguese: "Portuguese",
        dutch: "Dutch",
        swedish: "Swedish",
        norwegian: "Norwegian",
        danish: "Danish",
        finnish: "Finnish",
        polish: "Polish",
        czech: "Czech",
        hungarian: "Hungarian",
        greek: "Greek",
        turkish: "Turkish",
        arabic: "Arabic",
        hebrew: "Hebrew",
        hindi: "Hindi",
        thai: "Thai",
        vietnamese: "Vietnamese",
        indonesian: "Indonesian",
    },
    // -------------------- French --------------------
    fr: {
        english: "Anglais",
        french: "Français",
        french_belgium: "Français (Belgique)",
        spanish: "Espagnol",
        german: "Allemand",
        italian: "Italien",
        japanese: "Japonais",
        chinese: "Chinois",
        korean: "Coréen",
        russian: "Russe",
        portuguese: "Portugais",
        dutch: "Néerlandais",
        swedish: "Suédois",
        norwegian: "Norvégien",
        danish: "Danois",
        finnish: "Finnois",
        polish: "Polonais",
        czech: "Tchèque",
        hungarian: "Hongrois",
        greek: "Grec",
        turkish: "Turc",
        arabic: "Arabe",
        hebrew: "Hébreu",
        hindi: "Hindi",
        thai: "Thaï",
        vietnamese: "Vietnamien",
        indonesian: "Indonésien",
    },
};