name: Merge control

on:
  pull_request:
    types: [opened, reopened, closed, labeled, unlabeled, synchronize]

jobs:
  check-mep:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check merge conditions
        uses: actions/github-script@v6
        with:
          script: |
            const currentPRNumber = context.payload.pull_request.number;
            const currentPRLabels = context.payload.pull_request.labels.map(label => label.name);

            if (currentPRLabels.includes('MEP')) {
              console.log("No current PR for MEP");
              return;
            }

            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const otherMEPPRs = pullRequests.filter(pr =>
              pr.number !== currentPRNumber &&
              pr.labels.some(label => label.name === 'MEP')
            );

            if (otherMEPPRs.length > 0) {
              core.setFailed("Existing current PR for MEP");
            } else {
              console.log("Merge allowed.");
            }
