name: Notification de mise à jour des PRs

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, closed]

jobs:
  notify-all-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher l'événement repository_dispatch pour toutes les PRs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-pr-merge-restriction-for-mep
